### ISSUE TITLE
Cache results

### ISSUE THREAD

**Issue by Huji** [SQL-enwiki/ipcheck#1]
Each time an IP is queried, the results should be cached in a serialized fashion. I recommend caching for one week only (the graph on [this page](https://nl.wikipedia.org/wiki/Gebruiker:RonaldB/Open_proxy_fighting), as old as it is, suggests that to be a reasonable duration). There should also be a way to invalidate the cache on demand (perhaps requiring a CAPTCHA check).

The advantages are:

1) Faster response time for subsequent queries for that IP while the cache lasts
2) Fewer queries to upstream services
3) Less possibility of being blocked by upstream services

Any caching mechanism would do. Perhaps we should rewrite the code to use a framework with caching support ([Symfony](https://github.com/symfony/symfony) has a [cache](https://github.com/symfony/cache), and [Laravel](https://github.com/laravel/laravel) has supports [many caching mechanisms](https://laravel.com/docs/4.2/cache), as [does](https://www.codeigniter.com/userguide3/libraries/caching.html) [CodeIgniter](https://github.com/bcit-ci/CodeIgniter))

**Comment by MusikAnimal** [comment]
:+1: I've really only ever worked with https://github.com/symfony/cache, and can certainly vouch for it. You don't need Symfony to use it, and you can use a variety of adapters (file system being the easiest, works out of the box). Personally I don't think we need a framework just yet.

> There should also be a way to invalidate the cache on demand (perhaps requiring a CAPTCHA check).

I like this idea a lot too! Adding OAuth and restricting to experienced users I think is on the radar, from my conversations with @SQL-enwiki. This I assume would eliminate the need for a CAPTCHA.

**Comment by SQL-enwiki** [comment]
Yep, we were discussing this last night. The portscan results are already cached at the remote provider, and I'd like to do the same with the dnsbl / api hit results.

A week is probably the longest I'd want to go - if not maybe a little shorter, 3-5 days perhaps.

Once we get pull request #2 merged, that's the next thing I want to implement.

**Comment by SQL-enwiki** [comment]
Simple json caching added via 4d5fd8390597a4127b81c0a1113eb6e4c3e31afa and a8729b997d7a8e7f2a30e69b6884e80a1814f862

For right now, it's set for 1 week, we can adjust as needed down the line.

**Comment by SQL-enwiki** [comment]
Re-open, there still needs to be a way to invalidate the cache. This will depend on #4

**Comment by SQL-enwiki** [comment]
Cache invalidation is now active on the oauth branch as of 2615a3e

**Comment by SQL-enwiki** [comment]
Resolved, and merged as of 74e0997 - Not live on production yet, but will be by the end of the weekend
