### ISSUE TITLE
Button for some big wikis

### ISSUE THREAD

**Issue by revi** [SQL-enwiki/ipcheck#14]
Since the login dropdown defaults to enwiki, it is pretty annoying I have to scroll every time I browse the tools (I don't use it daily and Safari does a pretty good job at scrubbing the auth data for not-visited-for-long sites) I have to scroll and find meta from 800 wikis. Life would be more beautiful if we have some buttons for "click here to log in from enwiki" "or Meta" "or Commons" then the dropdowns.

**Comment by SQL-enwiki** [comment]
This shouldn't be too hard. The question is 'what constitutes a big wiki?'. I'd be happy to add en, commons, meta, but I would wonder where to draw the line? We can't include them all.

That being said, this is done.

Thanks for the suggestion!
