### ISSUE TITLE
Make access denied error message more descriptive

### ISSUE THREAD

**Issue by urbanecm** [SQL-enwiki/ipcheck#18]
![image](https://user-images.githubusercontent.com/10050467/63970941-b1a05480-caa5-11e9-841e-319ee19569a3.png)

This is what I get when I log in with my WMF account. Not telling much, perhaps adding "Only users with more than 500 edits and older than 30 days can use this tool" is possible?

**Comment by SQL-enwiki** [comment]
Resolved in be0d8e5 . Now says (for my tester) "I'm sorry, you can't use this application. Minimum edit count is 500, and you only have 10."

Also implemented whitelisting.
