### ISSUE TITLE
Allow users to enter more than one IP at once

### ISSUE THREAD

**Issue by urbanecm** [SQL-enwiki/ipcheck#22]
When you're looking at XY accounts, it's frequently useful to paste a bunch of IPs to the tool and get only those that are proxy, for instance. Originally thought about writing a sister tool asking IPCheck for the data through its API, but maybe it's good idea to bundle this into IPCheck?

**Comment by SQL-enwiki** [comment]
Hmm, I could probably allow the tool to do this, but it might require a bit of UI work to surface multiple results.

Might need to be limited (e.g. no portscanning, or refresh) to prevent abuse / overuse of finite resources.
