### ISSUE TITLE
Specialized API key for WHOIS tool

### ISSUE THREAD

**Issue by QEDK** [SQL-enwiki/ipcheck#24]
I filed https://github.com/whym/whois-gateway/pull/13 to include IPCheck as a useful tool but as it stands there's the OAuth verification that any user will have to go through (and then it loses the IP query, which is bad behaviour). I think it should be possible to create a specialized API endpoint that directly allows the tool to fetch a few results from IPCheck.

**Comment by SQL-enwiki** [comment]
At this time, I am not able to issue API keys for projects. You are able to use your api key (available at the bottom of the page) for your project, if you would like. However, I'm not sure if using the API to sidestep the restrictions on whom can use the tool would be ideal.

The OAuth behavior is new, and is being tracked in #25 .
