### ISSUE TITLE
Persist preloaded IP address through OAuth prompt

### ISSUE THREAD

**Issue by stwalkerster** [SQL-enwiki/ipcheck#25]
If I am logged into the IPCheck tool, and load a URL such as `https://ipcheck.toolforge.org/index.php?ip=129.205.113.145`, I am immediately taken to the results page for that IP address. This is the desired behaviour.

If I am not logged into IPCheck, I get redirected to an OAuth prompt. I accept the OAuth prompt, and on my return I am sent to `https://ipcheck.toolforge.org/index.php`, which prompts me to input an IP address. The tool should remember the requested IP address through the OAuth prompt, thus if I arrive at the tool with a request for a specific results page, I should be able to accept the OAuth prompt and be directed back to the requested results page.

The developer in me wants to suggest adding the IP to check to `$_SESSION`, then on return to the tool check whether there's something in `$_SESSION` and run that check instead of returning to the search box - there may be a better way that fits more closely with the tool's architecture though.

**Comment by SQL-enwiki** [comment]
I'm fairly sure I use $_SESSION specifically to store the IP across OAuth.

I just tested it, and it for sure behaves the way you describe.

I'll take a look at this in the next couple days and see if I can figure out why it doesn't work right.

**Comment by SQL-enwiki** [comment]
It looks like this is performed somewhere around line 130 of public_html/oauth.php . I can't see where it's set right now, but I could probably introduce it somewhere near line 72 of public_html/index.php .

**Comment by SQL-enwiki** [comment]
Fixed as of 2cd8bb1 and 6ca8c00
