### ISSUE TITLE
Allow WMF Staff to access the tool

### ISSUE THREAD

**Issue by davidbarratt** [SQL-enwiki/ipcheck#29]
**Problem**
WMF Staff sometimes need to make judgements on IP Addresses and are unable to access the tool.

**Proposed Solution**
Usernames that end with ` (WMF)` should be able to access the tool without restriction.

**Comment by SQL-enwiki** [comment]
The concerns I raised on my talkpage still need to be addressed (permlink: https://en.wikipedia.org/w/index.php?title=User_talk:SQL&oldid=952231860#Auto-approving_"_(WMF)"_accounts_at_IPCheck ).

I intend to build in enhanced / restricted functionality for certain groups in the future, and would prefer to have a way to validate that a " (WMF)" account actually belongs to a WMF staffer. 

At this time, these can be created by account creators, and (I think?) sysops. We've seen sysops compromised many times before.

**Comment by davidbarratt** [comment]
An alternative could be to use the global [staff](https://meta.wikimedia.org/wiki/Special:GlobalUsers/staff) group which should include anyone who would need access anyways.

**Comment by SQL-enwiki** [comment]
That would work for me. I wasn't sure if that would be too narrow. I'll get to work on it soon, shouldn't be too hard.

**Comment by SQL-enwiki** [comment]
It's been directly expressed to me by WMF that I should not spend further time on this tool. Sorry.
