### ISSUE TITLE
API

### ISSUE THREAD

**Issue by SQL-enwiki** [SQL-enwiki/ipcheck#3]
Write documentation for the API.

Write Access control for the API.

**Comment by MusikAnimal** [comment]
Note with #2 the API response format (key names, etc.) has changed... Presumably this is OK because there aren't any consumers yet. The nice thing is that moving forward, the data passed to the view is the same data used for the API, so we'll stay in sync.

**Comment by SQL-enwiki** [comment]
API key generation and use are now up and running on the oauth branch. API Documentation too.

We now have someone using the API as well!

**Comment by SQL-enwiki** [comment]
Resolved, and merged as of 74e0997
