### ISSUE TITLE
Access Control

### ISSUE THREAD

**Issue by SQL-enwiki** [SQL-enwiki/ipcheck#4]
For the main app - there should be some form of access control - preferably oauth.

What level should be required for access? 

EC? (Not all wikis have this, but a check for 30/500 shouldn't be too hard to write)
Admin? (Perhaps this could be a base requirement to allow portscanning?)

**Comment by MusikAnimal** [comment]
In my opinion the whole tool should be limited to editors with 500 edits / 30 days tenure, and not just port scanning. Sort of a BEANS thing... but then again I suppose the vandal is aware they're using an open proxy :)

At any rate, I suggest using https://github.com/wikimedia/mediawiki-oauthclient-php. This is the official PHP OAuth library and I've used it in many applications. It shouldn't be too difficult to set up (the biggest pain is setting up the OAuth consumer itself on-wiki).

**Comment by SQL-enwiki** [comment]
I have this working in the oauth branch, but I need to do more testing.

I wasn't able to use the oauth client framework linked above - it did not appear to be in a working state. I could get the demo to partially work, but that was after a lot of changes to the code. 

I ended up reusing a lot of code from here: https://tools.wmflabs.org/oauth-hello-world/ , and it does authorize correctly.

**Comment by SQL-enwiki** [comment]
OAuth, Logging, and cache invalidation are working properly now.

Access control is working properly, using the beta cluster.

I'm close to being ready to merge the oauth branch.

I'll need to set up a consumer on meta: https://meta.wikimedia.org/wiki/Special:OAuthConsumerRegistration/propose

We'll need to decide how the API is handled. Should I create an API key for each user, or have bots authenticate via oauth (is that possible?)

Once those items are settled, we should be ready to merge the oauth branch

**Comment by SQL-enwiki** [comment]
Add one more onto this - oauth has to be wikimedia wide, so we have to have the user choose what wiki they are from! Probably using the wiki table from meta_p, and using a dropdown populated with the dbname field.

**Comment by SQL-enwiki** [comment]
> Add one more onto this - oauth has to be wikimedia wide, so we have to have the user choose what wiki they are from! Probably using the wiki table from meta_p, and using a dropdown populated with the dbname field.

Resolved in 2615a3e

**Comment by SQL-enwiki** [comment]
I've gone ahead and proposed OAuth consumers at meta - https://meta.wikimedia.org/wiki/Steward_requests/Miscellaneous#OAuth_Enable_request_for_IPCheck .

API Handling still isn't done, but I should be able to finish that this weekend.

With a couple good days of testing from users on other wikis we should be good to launch oauth on production by next week hopefully.

**Comment by SQL-enwiki** [comment]
Resolved, and merged as of 74e0997
